<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\VideoCreator.Core\VideoCreator.Core.csproj" />
    <ProjectReference Include="..\VideoCreator.Media\VideoCreator.Media.csproj" />
    <ProjectReference Include="..\VideoCreator.Rendering\VideoCreator.Rendering.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
