window.VideoCreatorSampleMedia = [
  { name: 'Tropical Sunset Beach.jpg', url: 'assets/sample-beach.jpg' },
  { name: 'Alpine Glacial Lake.jpg', url: 'assets/sample-mountains.jpg' },
  { name: 'Cozy Morning Cafe.jpg', url: 'assets/sample-cafe.jpg' },
  { name: 'Cyberpunk Neon City.jpg', url: 'assets/sample-cyberpunk.jpg' },
  { name: 'Golden Autumn Forest.jpg', url: 'assets/sample-forest.jpg' }
];

window.VideoCreatorTemplates = [
  {
    id: "template-reel-fast-beats",
    name: "⚡ Viral Beat Drops Reel",
    description: "Fast 1.3s high-energy cuts with beat sync, push transitions, and crisp contrast.",
    category: "Social",
    aspectRatio: "9:16",
    photoDuration: 1.3,
    motion: "ZoomIn",
    transition: "Push",
    transitionDuration: 0.35,
    cropMode: "BlurBackground",
    suggestedTitle: "CAN'T STOP ⚡",
    thumbnail: "assets/sample-cyberpunk.jpg",
    musicTrack: "pop",
    effects: [{ type: "Contrast", intensity: 0.25 }]
  },
  {
    id: "template-reel-aesthetic-vlog",
    name: "🌸 Aesthetic Mini Vlog",
    description: "Warm pastel color tone, smooth gentle pan motion, and typewriter animated titles.",
    category: "Social",
    aspectRatio: "9:16",
    photoDuration: 2.4,
    motion: "Cinematic",
    transition: "CrossDissolve",
    transitionDuration: 0.6,
    cropMode: "BlurBackground",
    suggestedTitle: "A Day in My Life ✨",
    thumbnail: "assets/sample-cafe.jpg",
    musicTrack: "lofi",
    effects: [{ type: "Vintage", intensity: 0.35 }]
  },
  {
    id: "template-reel-fashion-glow",
    name: "✨ Fashion & Luxury Glow",
    description: "Dreamy highlight glow, slow zoom out, elegant vignette framing, and chic serif typography.",
    category: "Social",
    aspectRatio: "9:16",
    photoDuration: 3.0,
    motion: "ZoomOut",
    transition: "Fade",
    transitionDuration: 0.8,
    cropMode: "BlurBackground",
    suggestedTitle: "Golden Hour Style",
    thumbnail: "assets/sample-beach.jpg",
    musicTrack: "ambient",
    effects: [{ type: "Glow", intensity: 0.4 }]
  },
  {
    id: "template-reel-motivational",
    name: "🔥 Bold Motivation Reel",
    description: "Heavy high-contrast tone, upward slide cuts, and bold punchy typography.",
    category: "Social",
    aspectRatio: "9:16",
    photoDuration: 1.8,
    motion: "PanUp",
    transition: "SlideUp",
    transitionDuration: 0.4,
    cropMode: "Fill",
    suggestedTitle: "STAY FOCUSED 🔥",
    thumbnail: "assets/sample-forest.jpg",
    musicTrack: "edm",
    effects: [{ type: "Contrast", intensity: 0.3 }]
  },
  {
    id: "template-cinematic",
    name: "Cinematic Story",
    description: "Slow majestic zooms and cross-dissolves with subtle cinematic warmth.",
    category: "Cinematic",
    aspectRatio: "16:9",
    photoDuration: 3.8,
    motion: "Cinematic",
    transition: "CrossDissolve",
    transitionDuration: 0.8,
    cropMode: "BlurBackground",
    suggestedTitle: "A Cinematic Journey",
    thumbnail: "assets/sample-mountains.jpg",
    musicTrack: "ambient",
    effects: [{ type: "Cinematic", intensity: 0.5 }]
  },
  {
    id: "template-travel",
    name: "Travel & Adventure",
    description: "Fast-paced directional slides, bold punchy colors, and diagonal pans.",
    category: "Travel",
    aspectRatio: "9:16",
    photoDuration: 2.5,
    motion: "Diagonal",
    transition: "Push",
    transitionDuration: 0.5,
    cropMode: "Fill",
    suggestedTitle: "Wanderlust Chronicles ✈️",
    thumbnail: "assets/sample-beach.jpg",
    musicTrack: "pop",
    effects: [{ type: "Saturation", intensity: 0.25 }]
  },
  {
    id: "template-memories",
    name: "Golden Memories",
    description: "Warm vintage tones, soft fade transitions, and gentle pan motions.",
    category: "Memories",
    aspectRatio: "9:16",
    photoDuration: 3.2,
    motion: "ZoomIn",
    transition: "Fade",
    transitionDuration: 0.7,
    cropMode: "BlurBackground",
    suggestedTitle: "Unforgettable Moments",
    thumbnail: "assets/sample-forest.jpg",
    musicTrack: "acoustic",
    effects: [{ type: "Vintage", intensity: 0.4 }]
  },
  {
    id: "template-minimal",
    name: "Clean & Minimal",
    description: "Crisp, clean cuts with pure aesthetic balance and high contrast clarity.",
    category: "Minimal",
    aspectRatio: "1:1",
    photoDuration: 3.0,
    motion: "None",
    transition: "Fade",
    transitionDuration: 0.5,
    cropMode: "Fit",
    suggestedTitle: "A Simpler View",
    thumbnail: "assets/sample-cafe.jpg",
    musicTrack: "lofi",
    effects: []
  },
  {
    id: "template-wedding",
    name: "Wedding & Love Story",
    description: "Romantic slow dissolves, warm gentle zoom, and classic elegant typography.",
    category: "Romance",
    aspectRatio: "16:9",
    photoDuration: 4.0,
    motion: "ZoomIn",
    transition: "CrossDissolve",
    transitionDuration: 1.0,
    cropMode: "BlurBackground",
    suggestedTitle: "Our Love Story 💍",
    thumbnail: "assets/sample-beach.jpg",
    musicTrack: "ambient",
    effects: [{ type: "Glow", intensity: 0.3 }]
  }
];
