window.VideoCreatorTemplates = [
  {
    id: "template-reel-fast-beats",
    name: "⚡ Viral Beat Drops Reel",
    description: "Fast 1.2s high-energy cuts with beat sync, push transitions, and crisp contrast.",
    category: "Social",
    aspectRatio: "9:16",
    photoDuration: 1.3,
    motion: "ZoomIn",
    transition: "Push",
    transitionDuration: 0.35,
    cropMode: "BlurBackground",
    suggestedTitle: "CAN'T STOP ⚡",
    effects: [{ type: "Contrast", intensity: 0.25 }]
  },
  {
    id: "template-reel-aesthetic-vlog",
    name: "🌸 Aesthetic Mini Vlog",
    description: "Warm pastel color tone, smooth gentle pan motion, and typewriter animated titles.",
    category: "Social",
    aspectRatio: "9:16",
    photoDuration: 2.4,
    motion: "Cinematic",
    transition: "CrossDissolve",
    transitionDuration: 0.6,
    cropMode: "BlurBackground",
    suggestedTitle: "A Day in My Life ✨",
    effects: [{ type: "Vintage", intensity: 0.35 }]
  },
  {
    id: "template-reel-fashion-glow",
    name: "✨ Fashion & Luxury Glow",
    description: "Dreamy highlight glow, slow zoom out, elegant vignette framing, and chic serif typography.",
    category: "Social",
    aspectRatio: "9:16",
    photoDuration: 3.0,
    motion: "ZoomOut",
    transition: "Fade",
    transitionDuration: 0.8,
    cropMode: "BlurBackground",
    suggestedTitle: "Golden Hour Style",
    effects: [{ type: "Glow", intensity: 0.4 }]
  },
  {
    id: "template-reel-motivational",
    name: "🔥 Bold Motivation Reel",
    description: "Heavy high-contrast tone, upward slide cuts, and bold punchy typography.",
    category: "Social",
    aspectRatio: "9:16",
    photoDuration: 1.8,
    motion: "PanUp",
    transition: "SlideUp",
    transitionDuration: 0.4,
    cropMode: "Fill",
    suggestedTitle: "STAY FOCUSED 🔥",
    effects: [{ type: "Contrast", intensity: 0.3 }]
  },
  {
    id: "template-cinematic",
    name: "Cinematic Story",
    description: "Slow majestic zooms and cross-dissolves with subtle cinematic warmth.",
    category: "Cinematic",
    aspectRatio: "16:9",
    photoDuration: 3.8,
    motion: "Cinematic",
    transition: "CrossDissolve",
    transitionDuration: 0.8,
    cropMode: "BlurBackground",
    suggestedTitle: "A Cinematic Journey",
    effects: [{ type: "Cinematic", intensity: 0.5 }]
  },
  {
    id: "template-memories",
    name: "Golden Memories",
    description: "Warm vintage tones, soft fade transitions, and gentle pan motions.",
    category: "Memories",
    aspectRatio: "9:16",
    photoDuration: 3.2,
    motion: "ZoomIn",
    transition: "Fade",
    transitionDuration: 0.7,
    cropMode: "BlurBackground",
    suggestedTitle: "Unforgettable Moments",
    effects: [{ type: "Vintage", intensity: 0.4 }]
  },
  {
    id: "template-birthday",
    name: "Birthday Celebration",
    description: "Dynamic slide transitions with energetic motion and vibrant colors.",
    category: "Celebration",
    aspectRatio: "9:16",
    photoDuration: 2.5,
    motion: "ZoomOut",
    transition: "SlideLeft",
    transitionDuration: 0.5,
    cropMode: "BlurBackground",
    suggestedTitle: "Happy Birthday! 🎉",
    effects: [{ type: "Saturation", intensity: 0.3 }]
  },
  {
    id: "template-travel",
    name: "Travel & Adventure",
    description: "Fast-paced directional slides, bold punchy colors, and diagonal pans.",
    category: "Travel",
    aspectRatio: "9:16",
    photoDuration: 2.5,
    motion: "Diagonal",
    transition: "Push",
    transitionDuration: 0.5,
    cropMode: "Fill",
    suggestedTitle: "Wanderlust Chronicles ✈️",
    effects: [{ type: "Saturation", intensity: 0.25 }]
  },
  {
    id: "template-minimal",
    name: "Clean & Minimal",
    description: "Crisp, clean cuts with pure aesthetic balance and high contrast clarity.",
    category: "Minimal",
    aspectRatio: "1:1",
    photoDuration: 3.0,
    motion: "None",
    transition: "Fade",
    transitionDuration: 0.5,
    cropMode: "Fit",
    suggestedTitle: "A Simpler View",
    effects: []
  },
  {
    id: "template-wedding",
    name: "Wedding & Love Story",
    description: "Romantic slow dissolves, warm gentle zoom, and classic elegant typography.",
    category: "Romance",
    aspectRatio: "16:9",
    photoDuration: 4.0,
    motion: "ZoomIn",
    transition: "CrossDissolve",
    transitionDuration: 1.0,
    cropMode: "BlurBackground",
    suggestedTitle: "Our Love Story 💍",
    effects: [{ type: "Glow", intensity: 0.3 }]
  },
  {
    id: "template-promo",
    name: "Modern Commercial / Promo",
    description: "High-impact fast cuts, snappy push transitions, and bold high-contrast text overlays.",
    category: "Business",
    aspectRatio: "16:9",
    photoDuration: 2.0,
    motion: "PanRight",
    transition: "Push",
    transitionDuration: 0.4,
    cropMode: "Fill",
    suggestedTitle: "INTRODUCING THE FUTURE",
    effects: [{ type: "Contrast", intensity: 0.2 }]
  },
  {
    id: "template-retro",
    name: "Retro 90s Film",
    description: "Classic sepia & film grain tone grading, subtle vignettes, and typewriter typography.",
    category: "Vintage",
    aspectRatio: "1:1",
    photoDuration: 3.5,
    motion: "PanLeft",
    transition: "Fade",
    transitionDuration: 0.6,
    cropMode: "BlurBackground",
    suggestedTitle: "Vintage Memories",
    effects: [{ type: "Vintage", intensity: 0.5 }, { type: "Vignette", intensity: 0.4 }]
  }
];
